const customErrorCodes = {
  PERMISSION_DENIED_TO_RESOURCE: "PERMISSION_DENIED_TO_RESOURCE",
  RESOURCE_ALREADY_EXIST: "RESOURCE_ALREADY_EXIST",
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
};

export default customErrorCodes;
